### ISSUE TITLE
preview

### ISSUE THREAD

**Issue by Cs137** [nvim-telescope/telescope-bibtex.nvim#11]
Thanks for this nice tool!

I wonder whether it is possible to get a preview showing the key values. Sorry, it might sound stupid but I don't get how to set it up.

**Comment by noahares** [comment]
I am happy you like it! 
If I understand you correctly, this should already be visible in the default telescope preview window. 
Maybe your Terminal is not wide enough to display it?

**Comment by Cs137** [comment]
My apologies - I don't dare to say it, but it was indeed the reason.

**Comment by noahares** [comment]
No problem. Glad to have solved your issue.
