### ISSUE TITLE
[bugfix] Handle large bibtex files

### ISSUE THREAD

**Issue by noahares** [nvim-telescope/telescope-bibtex.nvim#12]
Loading large bibtex files consumes to much memory. Lazy loading of entries to be previewed should solve this problem.

**Comment by noahares** [comment]
@jghauser I think you mentioned this issue in a MR. Do large bib-files still present a problem?

**Comment by jghauser** [comment]
Hmm, I don't think that was me. My .bib file usually has about ~1500 entries, and it works without issues. Not sure what would happen with truly large collections. I don't really know how I would test memory consumption for telescope-bibtex precisely, but I can't see anything out of the ordinary.

**Comment by noahares** [comment]
Ok, then I probably misunderstood the error you mentioned here: https://github.com/nvim-telescope/telescope-bibtex.nvim/pull/9#issuecomment-869622103

**Comment by jghauser** [comment]
Oh, you're right, I had completely forgotten about that. I haven't come across this problem ever again. And I just tried with a library of around ~5000 entries, and it worked without issues!
