### ISSUE TITLE
global_files (custom bib file) issue.

### ISSUE THREAD

**Issue by VolkovIlia** [nvim-telescope/telescope-bibtex.nvim#13]
Hi.

Trying to use your plugin and it works fine with *bib files in cwd but I cant to determine custom file in config.

My config:

```
nnoremap <silent> ;f <cmd>Telescope find_files<cr>
nnoremap <silent> ;r <cmd>Telescope live_grep<cr>
nnoremap <silent> \\ <cmd>Telescope buffers<cr>
nnoremap <silent> ;; <cmd>Telescope help_tags<cr>
nnoremap <silent> ;b <cmd>Telescope bibtex<cr>

lua << EOF
local actions = require('telescope.actions')
-- Global remapping
------------------------------
require'telescope'.load_extension("bibtex")
require('telescope').setup{
  defaults = {
    mappings = {
      n = {
        ['q'] = actions.close
      },
    },
  },
  extensions = {
    bibtex = {
        format = 'markdown',
        depth = 1,
        global_files = {'/home/user/Library/bibtex/lib.bib'}
                }
       }
}

EOF

```

What I did wrong? It always shows cwd bib only

**Comment by noahares** [comment]
Hi, thanks for submitting this issue. I think you need to load the extension after the setup call.
When I try to load it before the setup function, the entries from the global file are not displayed. I hope this resolves your issue as well.
Another thing: `markdown` as a format does nothing. I think you are looking for `md`.

**Comment by VolkovIlia** [comment]
Thanks! 

All works fine!
