### ISSUE TITLE
Errors if jabref-meta tags are present

### ISSUE THREAD

**Issue by krissen** [nvim-telescope/telescope-bibtex.nvim#14]
By default, JabRef includes meta-tags in the following form at the end of a `bib`-file:
```
@Comment{jabref-meta: databaseType:biblatex;}

@Comment{jabref-meta: fileDirectoryLatex-krisniem-NAME.local:/FILEPATH;}
```

If present, the extension doesn't work, with the following error:
```
E5108: Error executing lua ...lescope-bibtex.nvim/lua/telescope/_extensions/bibtex.lua/76: attempt to index local 'label' (a nil value)
```

If I remove the JabRef meta-tags, the telescope extension works as expected.

Thank you for this extension! Much appreciated.

**Comment by noahares** [comment]
Yes, I did not filter for anything like that, because people might have custom tags that I do not want to mess with.
I will implement something to exclude such entries by ignoring them if the parsing fails or something like that.
