### ISSUE TITLE
How to add a format that doesn't introduce newlines?

### ISSUE THREAD

**Issue by krissen** [nvim-telescope/telescope-bibtex.nvim#15]
I'm trying to create a plain format that would simply enter the label of the entry, but nothing else.

A custom plain format, `cite_marker = '%s'` introduces one newline. How to suppress these?

EDIT: One newline is introduced, not two. Newline + enter insert mode. Effectively, `PrintLabel+ja`.

**Comment by noahares** [comment]
When I try to do it like this:

```
      custom_formats = {
        {id = 'myCoolFormat', cite_marker = '%s'}
      },
      format = 'myCoolFormat',
```

I get only the label, no newlines. Maybe something else is responsible for the newlines in you config?

**Comment by krissen** [comment]
Would you dare guess what configuration options might introduce newlines?

I have no custom telescope configuration apart from configuring the bibtex extension, thus:
```
require('telescope').setup {
  extensions = {
    bibtex = {
      depth = 1,
      custom_formats = {
        {id = 'plain', cite_marker = '%s'}
      },
      format = 'plain',
      global_files = { "/path/to/sources.bib" },
      search_keys = { 'author', 'year', 'title' },
    }
  }
}

require('telescope').load_extension("bibtex")
```
When calling `:Telescope bibtex<cr>` at X on line 3 I get the search window. Pressing enter for selecting an entry, the label is entered on line 3 and the cursor is moved to position Y on line 4, in insert mode. Doesn't matter if I call `:Telescope bibtex` from normal mode or insert mode. What happens is 1) label is printed; 2) effectively "ja" (one line down and enter insert mode).
```
1 text
2 more text
3 text XMyCitationLabel
4. sYecond line
```

**Comment by noahares** [comment]
I am a bit lost about where the 'j' would come from. The inserting process is a bit hacky and I might look for something better in the future. Basically the label is inserted at the cursor position and then I do 'ea' to put the user in insert mode after the inserted text (thinking about it, 'Ea' may be better). But again, I do not know why it would move a line down. Is this just happening for your custom format or also for `tex`?

**Comment by krissen** [comment]
Happens for `tex` as well. `\cite{key}` is inserted and equivalent to movement `ja` is executed. 

I call it through the following (lua) mapping; should it be done in some other fashion, perhaps?
```
local map = vim.api.nvim_set_keymap
local options = { silent = true, noremap = true }

map('n', '<leader>@@', '<cmd>Telescope bibtex<cr>', options)
map('i', '@@', '<cmd>Telescope bibtex<cr>', options)
```

**Comment by noahares** [comment]
The mappings look fine. I really cannot tell where this issue would come from. You can try to remove line 168 `vim.api.nvim_feedkeys("ea", "n", true)` and see where the cursor goes. Another thing you can try is calling `vim.api.nvim_put(...)` with some random stuff to see if that is done correctly. I will look for a better way to do the insertion some time in the future, but right now I do not have the time for that.

**Comment by krissen** [comment]
Without line 168, the cursor stops at the last character of key. That is, if bibtex key = "lorem", the cursor is at `m`.

It seems the behaviour I've been describing appears only if telescope-bibtex is invoked at the end of the line, not if there are trailing characters at the point where the cursor is on invocation.

Consider `nvim_put({lines}, {type}, {after}, {follow})`.

If I set `follow = false` I do not see the described behaviour regardless if I'm at the end of the line or not. That is, it seems that if the cursor was at the end of the line, `follow = true` led to cursor being moved to the next line.

Also, with `after = true`, if cursor was placed at the comma in the following setting `
12,34` the key was not inserted after `,` but after `3`. Setting `after = false` solved that issue.

However, with 
```
        vim.api.nvim_put({entry}, "", false, false)
        vim.api.nvim_feedkeys("ea", "n", true)
```
 and cursor at comma in `12,34`, the key was inserted properly (`12,lorem34`) _but the cursor was moved to 4!_ (It should, IMO, been moved between `m` and `3` --- that is, to the end of the key that was inserted.

The following lines give me the behaviour I'm personally expecting:
```
        vim.api.nvim_put({entry}, "", false, false)
        vim.api.nvim_feedkeys("la", "n", true)
```

With the above, it's working just as I'd like it to. Thanks!

**Comment by krissen** [comment]
Follow up. I believe the issue arose because of a different workflow. For me, I frequently cite several keys; I want to add page references, sometimes prefix text (i.e. `\cite[cf.][9]{lorem}` or `\cite{lorem,ipsum}`, etc). I've got snippets and whatnot to handle this, as well as my use of different cite-commands, such as `\parencite{}`, `\textcite{}`, `\parencites{}`, plain `\cite` and so on.

In the use-case where telescope-bibtex would insert the entire cite-command, complete with bib-key, the current setup works well (I imagine). For my use-case, I prefer handling 'the surrounding command' in other ways, and would like telescope-bibtex to merely insert the plain bib-key and nothing else (as it does with the `nvim_put` and `nvim_feedkeys` mentioned in the previous post.

I would thus suggest the addition of a new format, `plain`, which does only that, as described above, and that `nvim_put` and `nvim_feedkeys` would be conditional to the format used. Thus, telescope-bibtex could support both kinds of workflows.

**Comment by noahares** [comment]
This looks good for me as well: 
```
vim.api.nvim_put({entry}, "", false, false)
vim.api.nvim_feedkeys("la", "n", true)
```
I think I didn't pay attention what `nvim_put(.. true, true)` does when I implemented this. Thanks for helping me with this.

Regarding the `plain` format, this sounds like a resonable thing to provide out of the box. But why does the cursor need to be at the beginning of the inserted text (assuming that is what you mean)? I think this is rather specific for your workflow and not something others would expect the plugin to do.

**Comment by krissen** [comment]
Sounds good!

Not sure what you meant by that last thing about the cursor though. I must've been unclear at some point. 

I would expect the key to be inserted where the cursor is. And I would expect the cursor at the end of the inserted key, after insertion.

**Comment by noahares** [comment]
Yes ok, then we got the same thing in mind. I should probably implement a check whether bibtex was called from normal or insert mode to place the user in the right mode after the insertion.

**Comment by krissen** [comment]
Works great in current master. Thank you!

**Comment by noahares** [comment]
Hey @krissen I am about to revert the changes to `vim.api.nvim_put(...)`. I hope this does not break anything for you.
I implemented a new way to specify the format which should fit your workflow.
If you have `\cite[]{}` with the cursor between the {} in insert mode, you can call `:Telescope bibtex cite format=plain` to insert the label inside the {}. Similary doing the same with the cursor on { in normal mode will paste the entry inside the brackets as well.
If you already set `format='plain'` in the `setup`-function, everything should work as well.
Please let me know if any issues arise from this.

**Comment by krissen** [comment]
Gotcha! Thank you for the heads up; much appreciated.
