### ISSUE TITLE
Feature suggestion? Support more than three search keys

### ISSUE THREAD

**Issue by krissen** [nvim-telescope/telescope-bibtex.nvim#16]
If I read the code correctly, `search_keys` is hardcoded to be three in number at the most?

I'm not fluent enough in lua to suggest concrete code, but I'm wondering if it would be possible to support `non-fixed' number of search keys? Or at least more than three. 

Or mention in the documentation that `search_keys` should be set to no more than three.

Possibly it wouldn't be necessary if values shown in the preview wasn't tied to `search_keys`.

**Comment by noahares** [comment]
The default search keys are 3, but you can specify any number by setting the table in the `setup` function of telescope.
They are then set in the `register_extension` function at the bottom and the search string for matching is constructed from all the keys.

**Comment by krissen** [comment]
Just regarding the latter, in the preview, if I only specify `author` and `title` in the search keys, that is what I see in the preview; author and title. If I add the search key `year` I see that in the preview as well. Without it, I don't.

**Comment by noahares** [comment]
Are we talking about the same window? The 'searchbar' should only show the `search_keys` but the preview window (on the right of the searchbar and results with standard telescope config) should show the whole entry. If thats not the case, can you give me one of the entries, so I can debug it?

**Comment by krissen** [comment]
Oh! In that case I only see the searchbar, not the preview. 🤔 Something off with my telescope settings, probably!

**Comment by noahares** [comment]
If your window is to narrow in width (e.g. you use a tiling window manager and have 2 terminals side by side with one containing neovim and telescope), the preview is not shown. You can either try to make your terminal wider or rearrange the panels of telescope via the config (see their readme)

**Comment by krissen** [comment]
Thank you; resolved.
