### ISSUE TITLE
[extension request] Yanking the entire bibtex entry

### ISSUE THREAD

**Issue by ThSGM** [nvim-telescope/telescope-bibtex.nvim#18]
Hi!

In addition to the base \cite command, it would be very handy to be able to copy the entire .bib reference for the search result. 

My usage in this regard is like this. I always have a local .bib file in the same directory as my document, but then I add a master .bib file to the global search path. This is often useful when working on collaborative documents because you don't want to share your master bib file. Instead, you want to transfer in entries from the master bib file to the local file when the required entry is needed.

So for example, something like: 

`:Telescope bibtex-entry`

which yanks or yanks+pastes the corresponding entry would be useful.

**Comment by noahares** [comment]
Sounds like a good feature that is fairly straight to implement. I will look into it as soon as I have a bit more time :)

**Comment by noahares** [comment]
I just merged this feature, fell free to test it and give me feedback if anything does not work.

You can call it with `:Telescope bibtex entry`
