### ISSUE TITLE
[Enhancement] Allow setting custom .bib file(s)

### ISSUE THREAD

**Issue by jghauser** [nvim-telescope/telescope-bibtex.nvim#2]
It would be great if we could set the bibtex file (even better: list of files) in the settings. I use one (or two) master files for all my projects and would like to set this explicitly rather than depending on them to be in the working directory.

I might have some time to experiment getting this to work, though I'm very new to lua.

**Comment by Conni2461** [comment]
@noahares are you watching that repo :)

**Comment by noahares** [comment]
That sounds like a good feature to implement. I think the easiest and also most flexible way to achieve this is by adding a table with directory and file entries to the `ext_config`. Good thing, you posted this issue today, on weekends I have time to take care of this :) 
I will link the MR here, when I have it working.

**Comment by noahares** [comment]
> @noahares are you watching that repo :)

Thanks for the reminder :) Did not have my notification for issues turned on. No it is.

**Comment by noahares** [comment]
The features are merged and the config options can be found in the README. I will close these issues now, but feel free to reopen them, if there are any bugs :)

**Comment by jghauser** [comment]
First of all, thanks a ton for working on this so quickly! 

I can't seem to set any of the settings, not sure if I'm doing something wrong. Currently my telescope settings are the following:

```
local actions = require('telescope.actions')

require('telescope').setup{
  defaults = {
    mappings = {
      -- exit telescope when hitting esc
      i = {
        ["<esc>"] = actions.close
      }
    }
  },
  extensions = {
    bibtex = {
      format = 'md',
      global_files = { '/home/julian/Documents/library/main.bib' }
    }
  }
}
```

The stuff enabling closing of telescope with esc works, but none of the settings for bibtex work. I've also tried different values for `depth` and still I could only ever see entries from the `.bib` file in the cwd.

**Comment by noahares** [comment]
Hmm thats weird. I tried opening a `tex` document and set the `gobal_files` to a bib file in another project. I get all the entries without problems. Also deleting something at the end of the path and increasing `depth` still works.
Do you load the extension before configuring it? 
Otherwise your config looks fine from what I see.

**Comment by jghauser** [comment]
OK, my bad. I seem to have had some incompatible configs. Not exactly sure what was the issue, but it works now. Thanks!
