### ISSUE TITLE
Wrong search results and displays with key 'booktitle'

### ISSUE THREAD

**Issue by jghauser** [nvim-telescope/telescope-bibtex.nvim#21]
The following entry results in faulty search results and display.

```
@incollection{eilan_consciousness_2007,
  author = {Eilan, Naomi},
  booktitle = {Reading Merleau-Ponty: On Phenomenology of Perception},
  editor = {Baldwin, Thomas},
  publisher = {Routledge},
  title = {Consciousness, Self-Consciousness and Communication},
  year = {2007},
}
```

The entry shows up in telescope-bibtex as 'Eilan, Naomi (2007), Reading Merleau-Ponty: On Phenomenology of Perception'. Likewise, if I search for any of the words in the `title`, I don't find the entry. If I search for terms in the `booktitle`, the entry shows up. It seems that maybe when reading the `.bib`, the `booktitle` key is matched first, rather than the `title` which is further down in the entry. I have `search_keys = {'author', 'year', 'title'}` in my config.

**Comment by noahares** [comment]
Thanks for pointing this out. From a quick look at my code I think your guess at what causes this issue is correct. The fix should be relatively easy.
