### ISSUE TITLE
File type dependent format?

### ISSUE THREAD

**Issue by mnacamura** [nvim-telescope/telescope-bibtex.nvim#24]
Thanks for developing this nice extension!

I'd like to set `extensions.bibtex.format` depending on file type: for example, use `md` for `markdown` and `markdown.pandoc` but `tex` for `tex`.
How can I achieve this setting?

**Comment by noahares** [comment]
Thanks for opening this issue. I implemented this in #26 :)
Feel free to test this and give me feedback if anything is broken.
You can use it via `:Telescope bibtex cite format=markdown` for example.
For your use case the default should now work as well. If you do not specify a format in the `setup` call, the plugin should use the correct format based on the filetype.

**Comment by mnacamura** [comment]
Thanks you very much for creating the MR! I tested it and it worked well for me, except for automatic filetype detection.

Some Vim plugins provide a sort of sub-filetypes for markdown: `markdown.pandoc` by [vim-pandoc/vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax) and `markdown.gfm` by [rhysd/vim-gfm-syntax](https://github.com/rhysd/vim-gfm-syntax) as far as I know. When filetype is `markdown.*` instead of simple `markdown`, `:Telescope bibtex cite` inserts plain fallback.

It would be easy to set some `autocmd FileType markdown.pandoc,markdown.gfm ...` to cope with them, but IMHO it's convenient if `markdown.*` are automatically detected by telescope-bibtex. I don't know whether these markdown subtypes are widely accepted in the community, so I'm not sure if it is useful for people, though.

**Comment by noahares** [comment]
Hmm yes I see your point. As long as they all keep the `markdown.*` filetype format, this should be simple to do. 
For now, adding something like this to your config should do the job as well:
```
      custom_formats = {
        {id = 'markdown.pandoc', cite_marker = '@%s'}
      },
```

**Comment by noahares** [comment]
Since it does not break anything and was really easy to implement, I just did it, lol.
This respects user defined formats for markdown subtypes as well as provides default markdown format for subtypes of the form `markdown.*`

**Comment by mnacamura** [comment]
It works perfectly! Thanks a lot!
