### ISSUE TITLE
[Enhancement] Caching

### ISSUE THREAD

**Issue by jghauser** [nvim-telescope/telescope-bibtex.nvim#3]
Is there some way we could cache the results? For me, it takes a while to read a .bib file with a few thousand entries.

**Comment by Conni2461** [comment]
Makes sense. I am thinking someone can do a table like that:
```lua
local cache = {
  -- each file is a new entry
  {
    name = filename,
    last_modified = stats.mtime.sec,
    entries = { },
  },
}
```

And then each time when we are possibly reading in the file we can get the stats with `local stat = vim.loop.fs_stat(filename)` and can compare with `mtime.sec` if the file change. If yes we just read it again.

**Comment by Conni2461** [comment]
Also CC @noahares

**Comment by noahares** [comment]
Thanks for the `fs_stat` hint @Conni2461 
Caching sounds good for large bib files. I will put that onto my TODO as well.
