### ISSUE TITLE
Normalization of Citation Format Keys

### ISSUE THREAD

**Issue by mehalter** [nvim-telescope/telescope-bibtex.nvim#35]
I have many bibliography entries with different casing for the search keys. Could we have the picker normalize the entry keys before parsing the citations? Here is an example where a citation doesn't show up nicely in the picker even though it is valid bibtex:
![2022-03-13_22:17:32_screenshot](https://user-images.githubusercontent.com/1591837/158093698-ea4ac24e-cb87-4e44-a3ec-cc2fe54fadd0.png)

Here's a normal one that is working:

![2022-03-13_22:20:03_screenshot](https://user-images.githubusercontent.com/1591837/158093733-1c767114-01d7-4ed8-b795-311797f2ba62.png)

**Comment by noahares** [comment]
Jep, that's a bug. Should definitely normalize the keys. Thanks for pointing this out. I will have a look at it.

**Comment by noahares** [comment]
Should be fixed with #37 
Let me know if any issues remain!
