### ISSUE TITLE
`set wrap` for preview window

### ISSUE THREAD

**Issue by andy941** [nvim-telescope/telescope-bibtex.nvim#38]
First of all, thanks for making such a great extension. I love how simple yet effective it is.
The only thing that bugs me a bit is that there is no way to force wrapping of lines in the preview window. it's really useful when I'm trying to figure out which bib entry is the right one (i.e. looking at the abstract). 
I have `set wrap` active for .bib files but it doesn't seem to affect Telescope previews. Is that something that could be added on your end or by Telescope configuration?

![image](https://user-images.githubusercontent.com/49410235/165937690-55a5ddee-155e-486f-a4d8-155f16af4a9b.png)

Thanks,
Andrea

**Comment by noahares** [comment]
I think you are looking for this:

`autocmd User TelescopePreviewerLoaded setlocal wrap`

Source: https://github.com/nvim-telescope/telescope.nvim#previewers.

However it does not seem to work for me... It works with the builtin pickers but not with this plugin. I will dig into this and see I can get it to work.
