### ISSUE TITLE
[Enhancement] Allow setting different formats for insert

### ISSUE THREAD

**Issue by jghauser** [nvim-telescope/telescope-bibtex.nvim#4]
I would like to use telescope-bibtex with pandoc/markdown, but currently entries are formatted for latex. Could we have an option for markdown formatting (e.g. `@SomeEntry`). The most flexible solution would be to allow custom strings before and after the entry (and maybe fallback to latex as default). What do you think? 

If this is something you'd like to see in this program, I'd be happy to give it a shot.

**Comment by Conni2461** [comment]
Possible in setup or with opts. Similar to other issue. 

CC @noahares

**Comment by noahares** [comment]
I created this mainly with latex in mind. Did not even know you could use `@entry` in markdown! Do I understand that correctly: pandoc uses bibtex, so the .bib file can be used as with latex? Only the `\cite{entry}` gets replaced by `@entry`? If so, this should be easy to add.

**Comment by jghauser** [comment]
Pandoc can use bibtex files (in a variety of ways), yes! Usually, the user specifies the relevant .bib file in some way in the command, and pandoc then uses that information when generating files of various formats. And yes, the only thing to make this work from telescope-bibtex's perspective is to change the citation key from `\cite{entry}` to `@entry`.

More info here: https://pandoc.org/MANUAL.html#citations
