### ISSUE TITLE
Duplicate entries in picker

### ISSUE THREAD

**Issue by montdor** [nvim-telescope/telescope-bibtex.nvim#40]
Loving this super-useful extension; thank you for what you do!

I've run into a bug(?) wherein I am trying to put a citation in my file, and all of the options are coming up twice (see below). At first I thought that I was calling in the .bib file twice, but I tried it with a local file as well and got the same result. Happy to give more information and try to debug! 

![bibtex_duplicate](https://user-images.githubusercontent.com/43308016/185802285-36649cd0-b62b-496b-b36b-0f5f5bea528e.png)

**Comment by noahares** [comment]
Thanks for saying thanks!

Can you share your telescope-bibtex config so I can try to reproduce it?

**Comment by montdor** [comment]
Hi there. Sorry for the delay. Day jobs always get in the way. Here is my bibtex config from within my telescope config:

    bibtex = {
          -- Depth for the *.bib file
          depth = 1,
          -- Custom format for citation label
          custom_formats = {},
          -- Format to use for citation label.
          -- Try to match the filetype by default, or use 'plain'
          format = '',
          -- Path to global bibliographies (placed outside of the project)
          global_files = {"MYFILEPATHHERE"},
          -- Define the search keys to use in the picker
          search_keys = { 'author', 'year', 'title' },
          -- Template for the formatted citation
          citation_format = '{{author}} ({{year}}), {{title}}.',
          -- Only use initials for the authors first name
          citation_trim_firstname = true,
          -- Max number of authors to write in the formatted citation
          -- following authors will be replaced by "et al."
          citation_max_auth = 2,
          -- Context awareness disabled by default
          context = true,
          -- Fallback to global/directory .bib files if context not found
          -- This setting has no effect if context = false
          context_fallback = true,
          -- Wrapping in the preview window is disabled by default
          wrap = false,
        },

**Comment by noahares** [comment]
Thanks, I found the problem. Somehow entries of the global bib-file are listed 2 times (or even 3 times when it is in the current project). Not sure how that broke, but I will try to fix it in the next few days.

**Comment by anandkumar89** [comment]
Somehow I'm still facing the same issue. I've updated plugin to latest revision.

https://github.com/user-attachments/assets/46d8d74e-af13-460b-a1cb-5d5262438583

```{lua}
bibtex = {
	depth=2,
	format='plain',
	global_files = {'~/Dropbox/Apps/Overleaf/bib/library.bib'},
	search_keys = {'author', 'year', 'title'},
	context = true,
	wrap = false,
	}
```
