### ISSUE TITLE
print formatted citation does not give any output

### ISSUE THREAD

**Issue by emilBeBri** [nvim-telescope/telescope-bibtex.nvim#43]
Hi so printing the citekey works fine, but not the formatted citation. This is odd, am I doing something wrong or is there an issue?

vim.api.nvim_set_keymap('n', '<leader>zbb', ':Telescope bibtex <CR>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<leader>zbf', ':Telescope bibtex <C-C>', { noremap = true, silent = true })

I'd be happy to supply troubleshooting info but I have a dreadful feeling that I'm just not good enough at nvim to see something obvious here. On manjaro linux w. i3

**Comment by noahares** [comment]
Could you elaborate on what is happening when you try to insert the formatted citation? I am a bit confused by the 2 keybindings. Per default you should call `:Telescope bibtex` (either through command mode or a keybinding) and press control + c to insert the formatted citation. What basically happens is that `:Telescope bibtex` lets you choose the entry (via control n/p or arrow keys) and the way you confirm the selection decides how it is inserted (enter for citation key, control + c for formatted citation and control + e for pasting the whole entry).

**Comment by emilBeBri** [comment]
Ah I get it now, my mistake, sorry for the bother!

**Comment by emilBeBri** [comment]
Interestingly this bibtex entry:


```
@book{wooldridge2020introstats,
  author        = {Jeffrey M. Wooldridge},
  title         = {Introductory Econometrics: A Modern Approach},
  owner         = {Emil Begtrup-Bright},
  timestamp     = {2022-10-11},
  year          = {2020}
  isbn 			= {978-1337558860},
}
```

cannot be used w. the formatted citation, but works fine with the citekey as well as outputting the bibtex entry itself. When using ctrl-c in the menu, I get the error:

```
E5108: Error executing lua ...e-bibtex.nvim/lua/telescope/_extensions/bibtex/utils.lua:31: attempt to concatenate local 'str' (a nil value)
stack traceback:
        ...e-bibtex.nvim/lua/telescope/_extensions/bibtex/utils.lua:31: in function 'split_str'
        ...e-bibtex.nvim/lua/telescope/_extensions/bibtex/utils.lua:80: in function 'make_initials'
        ...e-bibtex.nvim/lua/telescope/_extensions/bibtex/utils.lua:105: in function 'abbrev_authors'
        ...lescope-bibtex.nvim/lua/telescope/_extensions/bibtex.lua:323: in function 'format_citation'
        ...lescope-bibtex.nvim/lua/telescope/_extensions/bibtex.lua:332: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:341: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

**Comment by emilBeBri** [comment]
Ah great OK cheers mate.  Yeah it seems the former is used more, I think like 1/5 of mine are in the format of the latter though, but I probably should convert to the more standard format just to avoid issues in the future. 

I'll probably just fix them individually everytime   I come across it in my library  then, e.g. everytime your (very nice and incredibly helpful) plugin does not output correctly.
