### ISSUE TITLE
`context=true` setting not respected

### ISSUE THREAD

**Issue by jamespeapen** [nvim-telescope/telescope-bibtex.nvim#46]
I'm having some trouble with the context in rmarkdown files where the bib file is not in the same directory. I can produce this error in empty rmarkdown files. If the bib file is is the same directory, I get entries populating the telescope window. If not, there has to be both a header specifying the bib file path *and* `:Telescope bibtex` has to be run with `context=true`.

Telescope-bibtex setup:

```lua
require("telescope").setup {
  extensions = {
    bibtex = {
      context = true,
      context_fallback = true,
    },
  },
}
```

YAML in my markdown header:
```
bibliography: ../references.bib
```
Entries show up only with when `:Telescope bibtex context=true` is run explicitly.
If the bib file is in the same directory, entries show up regardless of whether there is a header specifying the file or the `context` passed to `:Telescope bibtex` - it populates with both `context=true` and `context=false`.

**Comment by noahares** [comment]
Thanks for bringing attention to this. I have not developed that feature and therefore would have to take a deeper look into the code. Right now I am a bit short on time, but its on my radar!

**Comment by jamespeapen** [comment]
No worries! Let me know if I can help test anything.

**Comment by jamespeapen** [comment]
The issue here was that my telescope setup was broken up into multiple sections and the extensions setup were in a different section to the rest of the telescope config. So even though I had `context=true`, I had that in a different chunk on its own (like in my first post). When I put it all together, the context setting works. 

I'm not sure if its wrong to have the `require("telescope").setup {}` in multiple places, but this is the first time I've had an issue with it.

**Comment by noahares** [comment]
That's weird... I remember somebody had a similar problem were the config for bibtex was not setup correctly. They to solved it by changing up their telescope config. I had checked how other telescope plugin authors do their config and couldn't find any differences that would explain these issues. 
From what you are experiencing it could have something the setup function being run twice. This would explain why the settings go back to default. [here](https://github.com/nvim-telescope/telescope.nvim/blob/04af51dbfb17c2afa0b8d82b0e842e0638201ca9/lua/telescope/init.lua#L135) it seems like telescope updates the extensions config each time the `setup` function is called. I will look into it, why the config does not persist if the value doesn't change.

**Comment by noahares** [comment]
Ah already found the problem. When the context setting was implemented the setup function sets the option back to default if it is not present in the config table that is passed (i.e. the empty table in your case.

**Comment by noahares** [comment]
Should be fixed now. Let me know if not. Sorry for needing to rewrite your config.
