### ISSUE TITLE
custum_formats to define <cr> and <c-c>

### ISSUE THREAD

**Issue by engeir** [nvim-telescope/telescope-bibtex.nvim#49]
As far as I understand from the documentation, it is only possible to change the way `<cr>` works with the `custom_formats` and `format` fields. If I also want a different formatted citation, setting `citation_format` will change the behavior of `<c-c>` for all file types and custom formats.

This means that it is not possible to for example set formatted citation to be APA, then Chicago etc. with `Telescope bibtex format=APA`, `Telescope bibtex format=Chicago`, ...

Is my understanding of how this works correct? (I saw [this issue](https://github.com/nvim-telescope/telescope-bibtex.nvim/issues/30), but could not find that this cover different formatted citations).

This would also be useful since many different parsers exist for markdown files. One use case I have would be something like

```lua
...
extensions = {
    bibtex = {
        custom_formats = {
            {
                id = "revealjs",
                cite_marker = '<a href="https://doi.org/{{doi}}" data-citation-key="@{{label}}">{{author}} ({{year}})</a>',
                citation_format = '<div class="csl-entry" id="ref-smith2010" role="doc-biblioentry"> {{author}}, {{title}}, {{journal}}, {{year}}, vol. {{volume}}, no. {{number}}, p. {{pages}}.</div>',
            },
            {
                id = "hackmd",
                citation_format = '[^@{{label}}]: {{author}}, {{title}}, {{journal}}, {{year}}, vol. {{volume}}, no. {{number}}, p. {{pages}}.',
                cite_marker = "[^@%s]",
            },
        },
        format = { "revealjs", "hackmd" },
    },
},
...
```

**Comment by noahares** [comment]
I would need to look into this. I wrote this plugin for bibtex initially and support for markdown was added down the line by me and other contributors, but I never used it myself. I think this can be adjusted pretty easily. I plan on implementing the recent feature requests here when I have some time again (probably april). This will be on the list.
