### ISSUE TITLE
Custom keybindings

### ISSUE THREAD

**Issue by xarthurx** [nvim-telescope/telescope-bibtex.nvim#51]
Similar discussion here: https://www.reddit.com/r/neovim/comments/r77p1q/combining_luasnip_and_telescope/

When writing academic paper, it is often needed to switch between `\citep` (parenthesis cite) and `\citet` (context cite). 
Sometimes, when using `biblatex` style, `\autocite` is needed.

Is there a way to customize key bindings (besides the current `<cr>`, `C-e`, `C-c`) so that I can add customized text into the cursor position?

**Comment by xarthurx** [comment]
Or just the cited symbol without the `\cite{`, so that I can customize it with my own snippets.
With the current keybindings, I always need to insert a `\cite{xxx}` and manually change it to `\citep{xxx}`.

**Comment by xarthurx** [comment]
Thanks for the reply.
I finally achieved it by using the `custom format` to export plain format, and use the `luasnippet` to create my own snippets and bind it to different keybindings.

```lua
-- Typical Abbreviations
local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return{
  -- testing 
  s("hi",  -- LuaSnip expands this to {trig = "hi"}
    {
      t("Hello, world!"), 
    }
  ),

  -- citation: citep
  s("cp",
    {
      t("\\citep{"), i(1), t("}"), i(2)}, {
      callbacks = {
        [1] = {
          [events.enter] = function(_)
            return vim.cmd [[Telescope bibtex]]
          end
        }
      }
    }),

  s("ct",
    {
      t("\\citet{"), i(1), t("}"), i(2)}, {
      callbacks = {
        [1] = {
          [events.enter] = function(_)
            return vim.cmd [[Telescope bibtex]]
          end
        }
      }
    }),

  s("cc",
    {
      t(" "), i(1)}, {
      callbacks = {
        [1] = {
          [events.enter] = function(_)
            return vim.cmd [[Telescope bibtex]]
          end
        }
      }
    }),

}
```

**Comment by noahares** [comment]
That is really handy. I love the things you can do with luasnips.

**Comment by xarthurx** [comment]
Yes.

FYI, the “cc” option is for adding multiple citations into the same pair of parentheses.

This may also contribute to your future change as your current setup always add a “\cite{}” for each of the citation added through your plugin.

**Comment by noahares** [comment]
I have implemented custom keymappings in this PR #54, a usage example can be found here: https://github.com/nvim-telescope/telescope-bibtex.nvim/tree/refactor_user_actions#custom-mappings
I would appreciate some feedback before merging this if you want to test it.

Regarding multiple citations into the same parenthesis: I think that is still limited by telescope not supporting multiple selections, but I would need to check if it is implemented by now.

**Comment by xarthurx** [comment]
Hey, thanks for the update.

Unfortunately, I don't have too much time available for setting up the testing env (changing repo, using PR, etc.). But if you merge it into the main, I can test with my current vim set up (It is easier for me).

**Comment by xarthurx** [comment]
Hi Sorry, somehow I missed the last email for testing. Just test it, it works great. Thank you for the effort.
