### ISSUE TITLE
Support different citation_format depending on type [feature suggestion]

### ISSUE THREAD

**Issue by krissen** [nvim-telescope/telescope-bibtex.nvim#53]
It would be great if there would be several `citation_format`s, depending on the *type* of item. Like for instance,

>      citation_format_incollection = '{{author}}. ({{year}}). {{title}}. In {{editor}}, {{booktitle}}',
>      citation_format_article = '{{author}}. ({{year}}). {{title}}. {{journal}}, ({{number}}:{{volume}}). {{doi}}. Retrieved {{urldate}} from {{url}}.',
>      citation_format_book = '{{author}} ({{year}}), {{title}}.',

Citation format would be selected automatically, according to `@type` of item. 

Some users might appreciate different `c-X` commands for manual format according to specific types. Somewhat related to #49.

Maybe include a `citation_format_fallback` as well, or keep the current, plain `citation_format` as fallback, and so as to avoid a breaking change.

**Comment by noahares** [comment]
Sounds reasonable. Will put this on my list of feature requests I will look into once I got the time (sometimes during April).
Not sure what you mean by the `c-X` command tho... Do you mean that the citation based on the `@type` should be triggered by `c-X` ?

**Comment by krissen** [comment]
Sorry, was unclear. It seemed that the other bug report suggested different insert format commands. The `X` in `c-X` was meant as a general placeholder, to be replaced by keys; `c-a`, `c-b` etc. But I'm primarily interested in format according to type, so the `c-X` discussion would rather belong to the other issue/feature suggestion.

**Comment by noahares** [comment]
Alright, thanks for the clarification.

**Comment by tienlonghungson** [comment]
@krissen Does your recommended feature work by default? Or how should I set it up

**Comment by krissen** [comment]
@tienlonghungson Just follow the normal setup as described in the README. Specifically, formatted citations.

That said, I can't test to confirm at the moment myself, due to not having access to a computer.
