### ISSUE TITLE
Out of memory (and solution)

### ISSUE THREAD

**Issue by ashiklom** [nvim-telescope/telescope-bibtex.nvim#57]
For some reason, I got consistent crashes ("out of memory") when trying to use this plugin. With debug-by-print, I was able to narrow down the bug to the `while true` loop in `read_file`, and specifically to the final line in that loop: https://github.com/nvim-telescope/telescope-bibtex.nvim/blob/master/lua/telescope/_extensions/bibtex.lua#L114

The crash always happened, but not always at the same point in the file. Sometimes it read more entries, sometimes fewer.

My target Zotero isn't _that_ large --- about 5 MB --- so there should be plenty of memory (especially on my 32 GB RAM machine!).

Interestingly, I was able to fix (or work around) this problem by combining that `while` loop with the adjacent loop over entries, such that each raw entry is fully parsed right as it's read:

```lua
  local data = p:read()
  data = data:gsub('\r', '')
  local entry = ''
  while true do
    entry = data:match('@%w*%s*%b{}')
    if entry == nil then
      break
    end
    local label = entry:match('{%s*[^{},~#%\\]+,\n')
    if label then
       -- Do stuff...
    end
    data = data:sub(#entry + 2)
  end
```

With that fix, it takes a few seconds to do the initial parsing of the bibtex file, but after that, the package works exactly as I would have expected.

Relevant system information:
Windows Subsystem for Linux (v1)
Ubuntu 22.04
NVIM v0.10.0-dev

**Comment by noahares** [comment]
Thanks for pointing this out. I'd be happy to merge this fix. If you already have implemented it, can you open a PR?
