### ISSUE TITLE
Telescope bibtex does not show entries

### ISSUE THREAD

**Issue by fellajimed** [nvim-telescope/telescope-bibtex.nvim#60]
Hey,

When running `:Telescope bibtex`, nothing is shown and I am having the following error:

```
E5108: Error executing lua: ...lescope-bibtex.nvim/lua/telescope/_extensions/bibtex.lua:293: attempt to index a nil value
stack traceback:
        ...lescope-bibtex.nvim/lua/telescope/_extensions/bibtex.lua:293: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:252>
```

I am using `VimTex` and the references are successfully found from the global file variable. Here is my config:
```
require('telescope').setup {
  defaults = {
    ...
    pickers = {},
    load_extensions = { "yank_history", "bibtex" },
    extensions = {
      bibtex = {
        depth = 1,
        custom_formats = {},
        format = '',
        global_files = { '~/texmf/bibtex/bib/ZoteroBiblio.bib' },
        search_keys = { 'author', 'year', 'title', 'label' },
        citation_format = '{{author}} ({{year}}), {{title}}.',
        citation_trim_firstname = true,
        citation_max_auth = 2,
        context = false,
        context_fallback = true,
        wrap = false,
      },
    },
  }
}
```

And in my tex file I have at the end:
```
...
\bibliographystyle{apalike}
\bibliography{ZoteroBiblio}
```

**Comment by noahares** [comment]
Could you attach the bib-file? This seems like a parsing error.

**Comment by fellajimed** [comment]
Here is an example of my bib file (the entries are taken from arxiv):

```
@misc{he2015deep,
      title={Deep Residual Learning for Image Recognition}, 
      author={Kaiming He and Xiangyu Zhang and Shaoqing Ren and Jian Sun},
      year={2015},
      eprint={1512.03385},
      archivePrefix={arXiv},
      primaryClass={cs.CV}
}

@misc{simonyan2015deep,
      title={Very Deep Convolutional Networks for Large-Scale Image Recognition}, 
      author={Karen Simonyan and Andrew Zisserman},
      year={2015},
      eprint={1409.1556},
      archivePrefix={arXiv},
      primaryClass={cs.CV}
}

```


The error message added some explanation recently:
```
E5108: Error executing lua: ...lescope-bibtex.nvim/lua/telescope/_extensions/bibtex.lua:293: attempt to index field 'id' (a nil value)
```

**Comment by aghriss** [comment]
You'll have to change `context = false` to `true` and make sure the path to the global file is correct. I have the same issue and took me a while to realize what's happening. Why does `context` defaults to false?

@noahares  I've noticed some redundancy in the code. Willing to accept a re-write PR?

**Comment by noahares** [comment]
@aghriss Thanks, yes I would very much appreciate a rewrite-PR. The code has become a mess as this plugin is now way beyond my initial scope. I wanted to rewrite it for some time now, but I can't find the time to do it.

**Comment by aghriss** [comment]
@noahares  I'm almost done with the rewrite. Any efficient way to get in touch to wrap it up. It's faster to ask some questions instead of trying to figure out what some functions do.
Thanks

**Comment by fellajimed** [comment]
Thanks @aghriss and @noahares, it solved the issue.

**Comment by noahares** [comment]
@aghriss we can do discord. Same tag as on gh (noahares)

**Comment by Delta-SC** [comment]
Hi @fellajimed, this is an old issue, but I had the exact same problem and [this solution](https://github.com/nvim-telescope/telescope-bibtex.nvim/issues/10#issuecomment-807975423) from #10 worked for me. Hope that helps.
