### ISSUE TITLE
using {\o} in a field makes it unsearchable in the picker (this is the way to use foreign letters like the scandinavian "ø"

### ISSUE THREAD

**Issue by emilBeBri** [nvim-telescope/telescope-bibtex.nvim#62]
When inputting {\o}, which is the way to input the scandiniavian letter ø in bibtex, the field that it is in disappears from the picker and only {\o} is there.  

to reproduce, create such an entry in the .bib file and search for it:

```

@Book{hoeg1993smilla,
  author        = "H{\o}eg, Peter",
  title         = "Fr{\o}ken Smillas fornemmelse for sne",
}
```

the change a field so that {\o} is not there, and then the field is searchable again.

on endeavour linux , fully updated, info about nvim and telescope version (should also be fully updated)

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905

telescope-bibtex.nvim 0.04ms U Telescope._extensions.blbtex U telescope.nvim
dir /home/emil/.local/share/nvim/lazy/telescope-bibtex.nvim
url https://github.com/nvim-telescope/telescope-bibtex.nvim
branch master
commit e4dcf64
readme README.md


```

**Comment by noahares** [comment]
Thanks for bringing this to my attention. This was an issue with parsing "" and {} in one field value.
Should be fixed now.

**Comment by emilBeBri** [comment]
yes it works now, thank you!
