### ISSUE TITLE
Some citations are not showing up in the picker, even though they have no strange letters 

### ISSUE THREAD

**Issue by emilBeBri** [nvim-telescope/telescope-bibtex.nvim#67]
Hi, so I noticed some of my citations are not showing up in the picker. It is very odd. Consider this:

```

@Book{rawls1971theory,
  author        = {Rawls, John},
  title         = {A Theory of Justice},
  year          = {1971}
}



@Book{vervaeke2023allison, 
  title         = {A Theory of Justice2},
  author        = {Rawls, John},
  isbn          = {0-674-88014-5},
  year          = {1971}
}




```

The first one (rawls1971theory) shows up, the second one (vervaeke2023allison) does not.  However if I copy the first referece so the bib file contains this:

```




@Book{rawls1971theory,
  author        = {Rawls, John},
  title         = {A Theory of Justice},
  year          = {1971}
}


@Book{rawls1971theory,
  author        = {Rawls, John},
  title         = {A Theory of Justice},
  year          = {1971}
}

@Book{vervaeke2023allison, 
  author        = {Rawls, John},
  title         = {A Theory of Justice test },
  year          = {1971}
}
```

Now the first one is duplicated, and shows up twice. The second still does not show up.

The really weird thing if I copy the first ref (rawls1971theory) and copy-paste stuff into that, it shows up as well, like this:

```



```

so now rawls1971theory and test2023allison shows up, but vervaeke2023allison still does not. 

I have no idea why that is. There are only three fields, they contain the same stuff. The fields are in the same order. I have tried turning on Vims mode for seeing hidden characters and can see none. I have tried copying pasting through other programs to remove whatever formatting there might be and can see none. What can this possibly be about? Can you reproduce it? 

On Endeavour linux, fully updated. 

```
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

telescope-bibtex.nvim 6ms 0 telescope._extensions.bibtex  telescope.nvim
dir /home/emil/.local/share/nvim/lazy/telescope-bibtex.nvim
url https://github.com/nvim-telescope/telescope-bibtex.nvim
branch master
commit b10ec78
readme README.md


```

**Comment by noahares** [comment]
Sorry, for taking so long to reply. I was between some stuff and couldn't test it.
I created a small test project with a tex-file and a bib-file containing your 2 entries.
Both show up when I open the picker. Have you tried a minimal example as well? What is your telescope-bibtex config?

**Comment by emilBeBri** [comment]
No worries! It seemed to have vanished, if I manage to reproduce it I will re-open this. Otherwise I think you can consider it a random thing not worth spending time on.
