### ISSUE TITLE
None of my citations are showing up

### ISSUE THREAD

**Issue by tokisuno** [nvim-telescope/telescope-bibtex.nvim#69]
Title

I am using lazy.nvim to load my plugins. I have my citations file in my global_files{} var.

Whenever I am in a .md file and run the command, nothing pops up. If I am in an existing latex project and run the command, it returns only 2/3 of the citations used in this project. This seems to be the case with all of my citations that are not of the type "article"

Any help would be great!

![image](https://github.com/nvim-telescope/telescope-bibtex.nvim/assets/85533116/172ff282-93b6-4b99-a258-64a5856c2d32)

![image](https://github.com/nvim-telescope/telescope-bibtex.nvim/assets/85533116/2fec0b8e-2a44-475a-aee5-ecc8aa255f1f)

**Comment by noahares** [comment]
Could you provide a small part of your bib-file that shows the problem so I can try to reproduce it? Right now I suspect it's either something about the format of the entries or telescope's startup and config.

**Comment by tjex** [comment]
Just a heads up for others coming here. I'm pretty sure this issue was because the extension was being loaded _before_ the setup function. This requirement is also stated in the troubleshooting section of the readme (but, perhaps should be made more clear, as I also encountered this when I switched to lazyvim).

**Comment by tokisuno** [comment]
> Just a heads up for others coming here. I'm pretty sure this issue was because the extension was being loaded _before_ the setup function. This requirement is also stated in the troubleshooting section of the readme (but, perhaps should be made more clear, as I also encountered this when I switched to lazyvim).

I completely forgot I made this post. [I did end up figuring things out.](https://youtu.be/e56fTq1yFJw) but don't use it atm (my root partition is too small for LaTeX and I've been too lazy to resize).
