### ISSUE TITLE
Forcing plain even when format is specified

### ISSUE THREAD

**Issue by tokisuno** [nvim-telescope/telescope-bibtex.nvim#74]
![helpme](https://github.com/nvim-telescope/telescope-bibtex.nvim/assets/85533116/6e360ad9-33c6-4356-87e0-8ae79ccbf972)

I tried:
Telescope bibtex format=tex
Telescope bibtex format=markdown
Telescope bibtex format=md
Telescope bibtex format=zk (my custom format)

I tried a format_string from some other issue post on here and that didn't work either. I'm only getting forced plain.

**Comment by noahares** [comment]
I can't stop the gif, so looking at your config is difficult, could you post your config as text please?

**Comment by tokisuno** [comment]
https://github.com/tokisuno/nvim/commit/aa51c89f5d59d685be5b2beb6afc5f8271157045

this is the last commit from my nvim config from when i added the plugin.

**Comment by tokisuno** [comment]
bump (if you need anything else just lmk)

**Comment by noahares** [comment]
Thanks, will look into it when I have some time this week.

**Comment by tokisuno** [comment]
```return {
  {"nvim-telescope/telescope.nvim",
    dependencies = "nvim-telescope/telescope-bibtex.nvim",
    version = '0.1.5',
    keys = {{
      "<leader>fz",
      ":Telescope bibtex<CR>",
      desc = "Fuzzy [f]ind bibtex ([z]otero) references",
    }},
    opts = {
      extensions = {
        bibtex = {
          depth = 1,
          custom_formats = {
            {
              id = "zettel", cite_marker = "#%s"
            }
          },
          format = 'zettel',
          global_files = {
            "~/Dropbox/latex/bibs/clitics.bib",
            "~/Dropbox/latex/bibs/syntax.bib",
            "~/Dropbox/latex/bibs/philosophy.bib",
          },
          citation_max_auth = 2,
          context = false,
          context_fallback = true,
          wrap = false,
        },
      }
    },
    config = function (_, opts)
      require("telescope").setup(opts)
      require("telescope").load_extension("bibtex")
    end
  },
}

```

solved by making my config like this.

copied this from some random user's dotfiles, but now the config and everything seems to work !
